stl_directory: "data/structured_dataset/STL"      # Where your .stl files live
output_directory: "outputs/ply_with_noise"        # Where to save PLYs & depth maps
number_of_cameras: 10                             # # of views per model
radius: 1.0                                       # Camera-sphere radius (meters)
noise: 0.001                                      # Gaussian noise Ïƒ (meters)