stl_directory: "data/structured_dataset/STL" # Path to the STL files
output_directory:  "test_sample/ply_output_with_noise_test" # Output directory for the PLY files and the depth maps

number_of_cameras: 10
radius: 1
noise : 0.001